name: update-sources
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-sources
  cancel-in-progress: true

jobs:
  update-sources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: ./update
      - run: git config user.email mitchellh@users.noreply.github.com
      - run: git config user.name zig-overlay
      - run: |
          git add mirrors.json sources.json
          if git diff --cached --quiet; then
            exit 0
          fi
          git commit -m 'update Zig release metadata'
          git push origin main
